const $ = (s) => document.querySelector(s);
const months = ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const monthsGen = ['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];
const weekdays = ['воскресенье','понедельник','вторник','среда','четверг','пятница','суббота'];
const today = new Date(); today.setHours(0,0,0,0);
let currentUser, viewDate = new Date(today.getFullYear(), today.getMonth(), 1), selectedDay = null, editingShift = null;
const defaultData = {liza:{name:'Лиза',rate:45,shifts:[],overrides:{}},zhenya:{name:'Женя',rate:45,shifts:[],overrides:{}}};
function load(){ const data=JSON.parse(localStorage.getItem('myShiftsData') || JSON.stringify(defaultData)); if(data.anna||data.david)return {liza:{...(data.anna||defaultData.liza),name:'Лиза'},zhenya:{...(data.david||defaultData.zhenya),name:'Женя'}}; return data; }
function save(data){ localStorage.setItem('myShiftsData', JSON.stringify(data)); }
function dateKey(d){ const local = new Date(d.getTime()-d.getTimezoneOffset()*60000); return local.toISOString().slice(0,10); }
function getData(){ return load()[currentUser]; }
function setData(fn){ const all=load(); fn(all[currentUser]); save(all); }
function fmt(n){ return new Intl.NumberFormat('he-IL',{maximumFractionDigits:1}).format(n); }
function hoursOf(s){ if(s.hours!==undefined&&s.hours!=='')return Number(s.hours); const [a,b]=s.start.split(':').map(Number),[c,d]=s.end.split(':').map(Number); return Math.max(0,((c*60+d)-(a*60+b)-Number(s.break||0))/60); }
function dayStatus(key){ const data=getData(), d=new Date(key+'T12:00:00'), override=data.overrides[key]; return override ? override.status : ([0,1,2,3,4].includes(d.getDay())?'work':'off'); }
function shiftsFor(key){ return getData().shifts.filter(s=>s.date===key); }
function updateHeader(){ const d=getData(); $('#avatar').textContent=d.name[0]; $('#sidebar-name').textContent=d.name; $('#page-title').textContent=`Добрый день, ${d.name}!`; $('#today-label').textContent=`Сегодня ${today.getDate()} ${monthsGen[today.getMonth()]}, ${weekdays[today.getDay()]}`; }
function updateDashboard(){ const data=getData(), y=viewDate.getFullYear(),m=viewDate.getMonth(), end=new Date(y,m+1,0).getDate(); const shifts=data.shifts.filter(s=>{const d=new Date(s.date+'T12:00:00');return d.getFullYear()===y&&d.getMonth()===m}); const h=shifts.reduce((sum,s)=>sum+hoursOf(s),0), income=h*data.rate; let work=0; for(let i=1;i<=end;i++) if(dayStatus(dateKey(new Date(y,m,i)))==='work')work++;
  $('#dash-month').textContent=`${months[m]} ${y}`; $('#hours-stat').textContent=`${fmt(h)} ч`; $('#income-stat').textContent=`${fmt(income)} ₪`; $('#days-stat').textContent=work; $('#hours-note').textContent=shifts.length?`${shifts.length} смен(ы) внесено`:'смен пока нет'; $('#income-note').textContent=`ставка ${fmt(data.rate)} ₪/ч`; $('#days-note').textContent='по графику и отметкам'; $('#chart-total').textContent=`${fmt(income)} ₪`;
  const weeks=[0,0,0,0,0]; shifts.forEach(s=>{const day=new Date(s.date+'T12:00:00').getDate();weeks[Math.min(4,Math.floor((day-1)/7))]+=hoursOf(s)*data.rate}); const max=Math.max(...weeks,1); $('#bar-chart').innerHTML=weeks.map(v=>`<div class="bar-wrap"><div class="bar" title="${fmt(v)} ₪" style="height:${v?Math.max(6,v/max*100):2}%"></div></div>`).join('');
  const list=[]; for(let i=0;i<30&&list.length<4;i++){const d=new Date(today);d.setDate(today.getDate()+i);const k=dateKey(d), status=dayStatus(k); if(status==='work'||shiftsFor(k).length){const ss=shiftsFor(k);list.push(`<div class="upcoming-item"><span class="date-pill">${d.getDate()}<br>${months[d.getMonth()].slice(0,3)}</span><div><b>${weekdays[d.getDay()]}</b><small>${ss.length?`${ss[0].start}–${ss[0].end}`:'Рабочий день по графику'}</small></div><span class="right">${ss.length?fmt(hoursOf(ss[0]))+' ч':'по плану'}</span></div>`);}} $('#upcoming-list').innerHTML=list.join('')||'<p class="muted">В ближайшие дни нет смен.</p>';
}
function renderCalendar(){ const y=viewDate.getFullYear(),m=viewDate.getMonth(), first=new Date(y,m,1).getDay(),total=new Date(y,m+1,0).getDate(); $('#calendar-month').textContent=`${months[m]} ${y}`; let out=''; for(let i=0;i<first;i++)out+='<div class="day empty"></div>'; for(let i=1;i<=total;i++){const d=new Date(y,m,i),key=dateKey(d),status=dayStatus(key), ss=shiftsFor(key), ov=getData().overrides[key]; const isToday=key===dateKey(today); out+=`<button class="day ${status==='off'?'off-day':''} ${d.getDay()>4?'weekend':''} ${isToday?'today':''}" data-date="${key}"><span class="day-num">${i}</span>${ss.map((s,index)=>`<span class="shift-chip" data-shift-index="${index}">${s.start}–${s.end} · ${fmt(hoursOf(s))} ч</span>`).join('')}${ov?.status==='off'?`<span class="off-chip">${ov.reason||'Выходной'}</span>`:''}</button>`;} $('#calendar-grid').innerHTML=out; }
function render(){updateHeader();updateDashboard();renderCalendar();$('#rate-input').value=getData().rate;}
function showWelcome(){ if(!localStorage.getItem('myShiftsInstructionsSeen')) $('#welcome-modal').showModal(); }
function changeMonth(delta){viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+delta,1);render();}
function switchPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(`#${page}-page`).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('#page-title').textContent=page==='dashboard'?`Добрый день, ${getData().name}!`:page==='calendar'?'Календарь':'Настройки';}
function openShift(date='',shift=null,index=null){ editingShift=shift?{date,index}:null; $('#shift-modal-eyebrow').textContent=shift?'РЕДАКТИРОВАНИЕ СМЕНЫ':'НОВАЯ ЗАПИСЬ'; $('#shift-modal-title').textContent=shift?'Изменить смену':'Добавить смену'; $('#shift-submit').textContent=shift?'Сохранить изменения':'Сохранить смену'; $('#shift-date').value=shift?.date||date||dateKey(today); $('#shift-start').value=shift?.start||'09:00'; $('#shift-end').value=shift?.end||'17:00'; $('#shift-hours').value=shift?hoursOf(shift):8; $('#shift-break').value=shift?.break||0; $('#shift-note').value=shift?.note||''; $('#shift-modal').showModal(); }
$('#login-form').addEventListener('submit',e=>{e.preventDefault();if($('#password').value!=='1234'){ $('#login-error').textContent='Неверный пароль. Попробуйте 1234.';return;}currentUser=$('#user-select').value;sessionStorage.setItem('myShiftsUser',currentUser);$('#auth-screen').classList.add('hidden');$('#app').classList.remove('hidden');render();showWelcome();});
$('#logout').onclick=()=>{sessionStorage.removeItem('myShiftsUser');$('#password').value='';$('#app').classList.add('hidden');$('#auth-screen').classList.remove('hidden');};
$('#close-welcome').onclick=$('#welcome-ok').onclick=()=>{localStorage.setItem('myShiftsInstructionsSeen','1');$('#welcome-modal').close();};
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>switchPage(b.dataset.page)));$('#add-shift').onclick=()=>openShift();$('#prev-month').onclick=()=>changeMonth(-1);$('#next-month').onclick=()=>changeMonth(1);$('#month-picker').onclick=()=>{viewDate=new Date(today.getFullYear(),today.getMonth(),1);render();};$('#cal-prev').onclick=()=>changeMonth(-1);$('#cal-next').onclick=()=>changeMonth(1);$('#cal-today').onclick=()=>{viewDate=new Date(today.getFullYear(),today.getMonth(),1);render();};
$('#shift-form').addEventListener('submit',e=>{e.preventDefault();const s={date:$('#shift-date').value,start:$('#shift-start').value,end:$('#shift-end').value,hours:$('#shift-hours').value,break:$('#shift-break').value,note:$('#shift-note').value};if(hoursOf(s)<=0){alert('Укажите количество часов больше нуля.');return;}setData(d=>{if(editingShift){const original=d.shifts.filter(x=>x.date===editingShift.date)[editingShift.index],position=d.shifts.indexOf(original);if(position>=0)d.shifts[position]=s;}else d.shifts.push(s);});$('#shift-modal').close();render();});
$('#calendar-grid').addEventListener('click',e=>{const cell=e.target.closest('[data-date]');if(!cell)return;selectedDay=cell.dataset.date;const chip=e.target.closest('[data-shift-index]');if(chip){const index=Number(chip.dataset.shiftIndex);openShift(selectedDay,shiftsFor(selectedDay)[index],index);return;}const d=new Date(selectedDay+'T12:00:00'),ov=getData().overrides[selectedDay];$('#day-modal-title').textContent=`${d.getDate()} ${monthsGen[d.getMonth()]}`;$('#day-modal-copy').textContent=shiftsFor(selectedDay).length?'Нажмите на фиолетовую отметку смены, чтобы изменить её часы. Здесь можно изменить статус дня.':'Отметьте дополнительный выходной или верните день в рабочий график.';$('#day-status').value=ov?.status||dayStatus(selectedDay);$('#day-reason').value=ov?.reason||'';$('#day-modal').showModal();});
$('#day-form').addEventListener('submit',e=>{e.preventDefault();const status=$('#day-status').value,reason=$('#day-reason').value.trim();setData(d=>{const standard=[0,1,2,3,4].includes(new Date(selectedDay+'T12:00:00').getDay())?'work':'off';if(status===standard&&!reason)delete d.overrides[selectedDay];else d.overrides[selectedDay]={status,reason};});$('#day-modal').close();render();});
$('#save-settings').onclick=()=>{const rate=Number($('#rate-input').value);if(rate>0){setData(d=>d.rate=rate);render();alert('Настройки сохранены.');}};document.querySelectorAll('.close-modal').forEach(b=>b.onclick=()=>b.closest('dialog').close());
currentUser=sessionStorage.getItem('myShiftsUser');if(['liza','zhenya'].includes(currentUser)){$('#auth-screen').classList.add('hidden');$('#app').classList.remove('hidden');render();showWelcome();}else sessionStorage.removeItem('myShiftsUser');
